### ISSUE TITLE
Update bower.json to be angular-percentage-filter

### ISSUE THREAD

**Issue by dkhunt27** [vpegado/angular-percentage-filter#5]
The bower package is incorrectly named angular-percentage-directive

**Comment by sgerrand** [comment]
:no_good:

This change broke deployment of multiple applications for me. Consider creating a new package in Bower for these kind of breaking changes. :person_frowning:

**Comment by vpegado** [comment]
@sgerrand I'm sorry for the inconvenience.
This repo was never intended to be registered as `angular-percentage-directive` in the first place and it was hogging the name for no good reason. So on request I decided to unregister it on the false assumption that no one was using it on the old name.

[Reaction video](https://www.youtube.com/watch?v=7rr88Szc5q0)
